name: "CI"

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '22 2 */5 * *' #2:22 every 5 days

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out repository under $GITHUB_WORKSPACE
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image that'll build our package
        run: docker build -t squid-builder .

      - name: Make the output folder
        run: mkdir sb-tmp

      - name: Run the build container
        run: docker run -v $(pwd)/sb-tmp:/sb-tmp squid-builder

      - name: Delete release and tag
        uses: dev-drprasad/delete-tag-and-release@v0.1.1
        with:
          delete_release: true
          tag_name: latest-stable-squid
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Latest-ish Stable Squid
          tag_name: latest-stable-squid
          draft: false
          prerelease: false
          body: Debian Stable Squid packages with (Open)SSL and tproxy support. 
          files: |
            ./sb-tmp/squid*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
